### ISSUE TITLE
Add option to skip bundling of specified modules

### ISSUE THREAD

**Issue by ChildishGiant** [Benjamin-Dobell/luabundle#12]
Socket is part of the default libs but I can't seem to import it. I've added `\Lua\5.1\lua\?.lua` but I then have the issue of `cause: ModuleResolutionError: Could not resolve module 'socket.core' required by 'socket'`

**Comment by abtonc** [comment]
That's mostly because you are trying to import a module that is outside of "__root" (aka default rootModuleName in options)

**Comment by Benjamin-Dobell** [comment]
`socket.core` is native library so `luabundle` is unable bundle it. At present luabundle intentionally fails in this situation as the bundle _may_ not run in the destination environment i.e. if socket is unavailable.

That said, there probably ought to be an additional option where you can provide an array of module names that are ignored during bundling. That way if you're certain the destination environment has `socket`/`socket.core` you'd be able to exclude them from bundling.

**Comment by willwatson27** [comment]
Do you have a preference for how this is implemented? Putting a guard at the top of this for loop does the trick for my basic use case but I'm not sure what else I need to take into consideration.

```typescript
if (ignoredModules.has(requiredModule)) {
  continue
}
```
https://github.com/Benjamin-Dobell/luabundle/blob/489855cb8572b026e158b72718ae0995974a2dcd/src/bundle/process.ts#L73-L85

**Comment by Benjamin-Dobell** [comment]
@willwatson27 I think that ought to work as the simplest location to insert the ignore logic. However, it might be nice to accept an array which can hold both strings and regexps, than a set of strings representing module names. With regex it'll make it much easier to ignore entire libraries.

**Comment by Benjamin-Dobell** [comment]
Implemented by @Dreagonmon in https://github.com/Benjamin-Dobell/luabundle/pull/18
