### ISSUE TITLE
Usel `load` calls to preserve line numbers for errors

### ISSUE THREAD

**Issue by jamestalmage** [Benjamin-Dobell/luabundle#6]
Store contents of bundled files as Lua strings, and use the `load` function to hydrate them back to executable code. Preserves line numbers of errors.

Disable when outputting for production.

(I'm happy to contribute PR's for most of these ideas).

**Comment by Benjamin-Dobell** [comment]
Unfortunately, I'm not keen on this one as luabundle was predominantly written for environments that don't actually support `load`. Yep, a pain!

Also, even in environments where `load` is an option, I think this may make debugging a lot more difficult, as the debugger would need to be expose the contents of `load`ed chunks in a way that an IDE can fetch the contents, store them as a temporary (or virtual) file, and display the contents in the IDE.

Instead it's expected that the tooling and/or debugger can perform source mapping of error lines. Basically that's the same approach taken by JS tooling. The key difference here is that `luabundle` _doesn't_ generate a true source-map. Instead you're able to perform mapping by using luabundle's `unbundle` functionality, as you can provide it a bundle and it'll return the module contained within, each with details of their location within the bundle (https://github.com/Benjamin-Dobell/luabundle#unbundled-data).

The approach described above is already working in practice as it's integrated in the [Tabletop Simulator Atom package](https://github.com/Berserk-Games/atom-tabletopsimulator-lua).

**Comment by jamestalmage** [comment]
I am considering this as a build tool for an environment that does.

Any objection to refactoring in a way that exposes an API necessary to do what I need? I'd rather write a wrapper than fork the project.

**Comment by Benjamin-Dobell** [comment]
I certainly understand the motivation, and I do see value in it. It's just that I'm presently (perhaps incorrectly) expecting that value to be small relative to the additional complexity associated with the feature. However, I'm quite happy to be shown otherwise.

As such you're quite welcome to submit a PR, and I'll assess the maintenance burden and additional ecosystem complexity (bundle output variants) based on the PR. However, I don't want to give you the wrong impression and you spend a huge amount of time/effort with the belief that I'm definitely going to merge this functionality.

**Comment by Benjamin-Dobell** [comment]
I should mention that you can probably achieve this (at least in the simple case) without modifying luabundle at all. Instead you ought to be able to `postprocess` option/callback.

However, if this were to be an officially supported feature you'd probably want to drop the additional layer of runtime indirection, and support unbundling via metadata changes that indicate this is a `load` bundle would be required. It may not be _too_ difficult to get working.

**Comment by jamestalmage** [comment]
Yes. I would considered `postprocess`, and that would definitely be my goto if this can't become part of core.

If I do tackle this, I'd need to understand unbundling. I mean, I understand the concept (it's not complicated), I just need to see why/how unbundling is being consumed.
