### ISSUE TITLE
Useless code?

### ISSUE THREAD

**Issue by ikegami** [Benjamin-Dobell/luabundle#8]
https://github.com/Benjamin-Dobell/luabundle/blob/b5c0d105e73f19ee3c4862b070e7521857a7d62f/src/bundle/process.ts#L87-L91

The code linked above sets `content`, but the variable isn't used anywhere else. So this code doesn't appear to have any purpose.

**Comment by ikegami** [comment]
*sigh*. Nevermind, I thought the function ended sooner than it did.

**Comment by Benjamin-Dobell** [comment]
Line 98
